### ISSUE TITLE
uv_try_write returns UV_EAGAIN when ECONNRESET?

### ISSUE THREAD

**Issue by hh9527** [libuv/libuv#1013]
```c
uv_buf_t b;
while (conn->obuf_size > 0) {
  int size = get_uv_buf(conn, &b);
  int n = uv_try_write((uv_stream_t*)&conn->stream, &b, 1);
  if (n == UV_EAGAIN) {
    // when client side ECONNRESET, n will be UV_EAGAIN
    n = 0;
  } else if (n < 0) {
    handle_error(n);
    return;
  }

  size -= n;
  consume_obuf(conn, n);

  if (size > 0) {
    conn->writing = get_uv_buf(conn, &b);

    // CRASH here
    int status = uv_write(&conn->wreq, (uv_stream_t*)&conn->stream, &b, 1, write_cb);
    if (status < 0) handle_error(status);
    return;
  }
}
```

when client RESET, `uv_try_write` returns UV_EAGAIN, and next `uv_write` **crash**.
gdb info:
```
Program received signal SIGPIPE, Broken pipe.
0x00007ffff6f32ccd in write () from /lib/x86_64-linux-gnu/libpthread.so.0

(gdb) info stack
#0  0x00007ffff6f32ccd in write () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000046d978 in uv__write (stream=0x945d90) at ../deps/libuv/src/unix/stream.c:828
#2  0x000000000046f0b0 in uv_write2 (req=0x945c80, stream=0x945d90, bufs=0x7fffffffa600, nbufs=1, send_handle=0x0, cb=0x44ff9c <write_cb>) at ../deps/libuv/src/unix/stream.c:1419
#3  0x000000000046f155 in uv_write (req=0x945c80, handle=0x945d90, bufs=0x7fffffffa600, nbufs=1, cb=0x44ff9c <write_cb>) at ../deps/libuv/src/unix/stream.c:1444
#4  0x00000000004501c5 in do_flush (client=0x945c00) at ../src/dobox.c:137
#5  0x000000000045253d in dbx_client_send (client=0x945c00, dataq=0x9a5ea8) at ../src/dobox.c:772
#6  0x0000000000450981 in after_work_cb (req=0x9a5e10, status=0) at ../src/dobox.c:300
#7  0x0000000000461d13 in uv__queue_done (w=0x9a5e68, err=0) at ../deps/libuv/src/threadpool.c:257
#8  0x0000000000461c28 in uv__work_done (handle=0x7fffffffdef0) at ../deps/libuv/src/threadpool.c:236
#9  0x000000000046441c in uv__async_event (loop=0x7fffffffde40, w=0x7fffffffe000, nevents=1) at ../deps/libuv/src/unix/async.c:98
#10 0x0000000000464580 in uv__async_io (loop=0x7fffffffde40, w=0x7fffffffe008, events=1) at ../deps/libuv/src/unix/async.c:138
#11 0x0000000000473db9 in uv__io_poll (loop=0x7fffffffde40, timeout=-1) at ../deps/libuv/src/unix/linux-core.c:382
#12 0x00000000004650ae in uv_run (loop=0x7fffffffde40, mode=UV_RUN_DEFAULT) at ../deps/libuv/src/unix/core.c:352
#13 0x00000000004523f0 in dbx_run (env=0x7fffffffde40, argc=11, argv=0x7fffffffe478) at ../src/dobox.c:746
#14 0x00000000004526b5 in main (argc=11, argv=0x7fffffffe478) at ../src/dobox.c:803
```

**Comment by txdv** [comment]
You posted the stack, but what is the actual crash message?

**Comment by hh9527** [comment]
@txdv My mistake, the program crashed with a SIGPIPE. I have update the comment.

**Comment by saghul** [comment]
@hh9527 you need to ignore SIGPIPE, otherwise your program will crash if you try to write to a closed socket. If you ignore SIGPIPE you'll get EPIPE error.
