### ISSUE TITLE
uv__epoll_wait hang

### ISSUE THREAD

**Issue by pszemus** [libuv/libuv#1275]
Hello
I'm writing a C++ application for non-blocking file downloading based on [curl/curl/docs/examples/multi-uv.c](https://github.com/curl/curl/blob/master/docs/examples/multi-uv.c).
After successfully fullfiling ~3-4k download operations, my application hangs on `uv__epoll_wait`:
```gbt
(gdb) bt
#0  0x00007f81fa6fd239 in syscall () from /lib64/libc.so.6
#1  0x00000000005a434a in uv__epoll_wait (epfd=<optimized out>, events=events@entry=0x7f81f5c359d0, nevents=nevents@entry=1024, timeout=timeout@entry=1000) at src/unix/linux-syscalls.c:321
#2  0x00000000005a27bf in uv__io_poll (loop=loop@entry=0x865d00 <default_loop_struct>, timeout=1000) at src/unix/linux-core.c:271
#3  0x00000000005994c4 in uv_run (loop=0x865d00 <default_loop_struct>, mode=UV_RUN_DEFAULT) at src/unix/core.c:352
#4  0x0000000000414438 in imageresizer::engine::FileDownloader::StartLoop (this=0x7ffc13bb6860) at src/engine/FileDownloader.cpp:102
#5  0x000000000041613e in std::__invoke_impl<void, void (imageresizer::engine::FileDownloader::* const&)(), imageresizer::engine::FileDownloader*>(std::__invoke_memfun_deref, void (imageresizer::engine::FileDownloader::* const&)(), imageresizer::engine::FileDownloader*&&) (__f=@0xfbab00: (void (imageresizer::engine::FileDownloader::*)(imageresizer::engine::FileDownloader * const)) 0x41437a <imageresizer::engine::FileDownloader::StartLoop()>, 
    __t=<unknown type in /opt/WP/imageresizer-worker/dist/Debug/GNU-Linux/imageresizer-worker, CU 0x16b92, DIE 0x2138b>) at /usr/include/c++/6.3.1/functional:227
#6  0x00000000004160cb in std::__invoke<void (imageresizer::engine::FileDownloader::* const&)(), imageresizer::engine::FileDownloader*>(void (imageresizer::engine::FileDownloader::* const&)(), imageresizer::engine::FileDownloader*&&) (
    __fn=@0xfbab00: (void (imageresizer::engine::FileDownloader::*)(imageresizer::engine::FileDownloader * const)) 0x41437a <imageresizer::engine::FileDownloader::StartLoop()>, 
    __args#0=<unknown type in /opt/WP/imageresizer-worker/dist/Debug/GNU-Linux/imageresizer-worker, CU 0x16b92, DIE 0x2138b>) at /usr/include/c++/6.3.1/functional:251
#7  0x000000000041607c in std::_Mem_fn_base<void (imageresizer::engine::FileDownloader::*)(), true>::operator()<imageresizer::engine::FileDownloader*>(imageresizer::engine::FileDownloader*&&) const (this=0xfbab00, 
    __args#0=<unknown type in /opt/WP/imageresizer-worker/dist/Debug/GNU-Linux/imageresizer-worker, CU 0x16b92, DIE 0x2138b>) at /usr/include/c++/6.3.1/functional:604
#8  0x0000000000416047 in std::_Bind_simple<std::_Mem_fn<void (imageresizer::engine::FileDownloader::*)()> (imageresizer::engine::FileDownloader*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0xfbaaf8)
    at /usr/include/c++/6.3.1/functional:1391
#9  0x0000000000415f95 in std::_Bind_simple<std::_Mem_fn<void (imageresizer::engine::FileDownloader::*)()> (imageresizer::engine::FileDownloader*)>::operator()() (this=0xfbaaf8) at /usr/include/c++/6.3.1/functional:1380
#10 0x0000000000415f74 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (imageresizer::engine::FileDownloader::*)()> (imageresizer::engine::FileDownloader*)> >::_M_run() (this=0xfbaaf0)
    at /usr/include/c++/6.3.1/thread:196
#11 0x00007f81fb1b95cf in ?? () from /lib64/libstdc++.so.6
#12 0x00007f81fa9c95ca in start_thread () from /lib64/libpthread.so.0
#13 0x00007f81fa7030ed in clone () from /lib64/libc.so.6
```
```bash
$ strace -p 11985
strace: Process 11985 attached
epoll_wait(8, [], 100, 0)               = 0
epoll_pwait(8, [], 100, 800, [], 8)     = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, [], 100, 1000, [], 8)    = 0
epoll_pwait(8, ^Cstrace: Process 11985 detached
 <detached ...>
```
What else can I do to debug this situation?
Maybe it's related to: nodejs/node#11307

I'm compiling against:
- libuv 1.11.0
- curl 7.53.1

**Comment by bnoordhuis** [comment]
I don't think this is a libuv bug so I'm going to ask you to post it to the mailing list.  We use the issue tracker for bug reports and feature requests, the mailing list for general support.  Thanks.
