### ISSUE TITLE
Assertion failed in uv__stream_connect

### ISSUE THREAD

**Issue by vertextao** [libuv/libuv#1437]
* **Version**: 1.x
* **Platform**: `Linux test10vm3 2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 x86_64 x86_64 GNU/Linux`

```
#9  0x00007fcbacecd710 in __assert_fail (assertion=0x1b99b50 "(((const QUEUE *) (&(stream->loop)->active_reqs) == (const QUEUE *) (*(QUEUE **) &((*(&(stream->loop)->active_reqs))[0]))) == 0)", 
    file=0x1b99891 "src/unix/stream.c", line=1365, function=0x1b99ef0 "uv__stream_connect") at assert.c:105
#10 0x000000000166306d in uv__stream_io ()
#11 0x0000000001667198 in uv__io_poll ()
#12 0x000000000165d4d8 in uv_run ()
```

```c++
static void uv__stream_connect(uv_stream_t* stream) {
...
  stream->connect_req = NULL;
  uv__req_unregister(stream->loop, req);
...
}

#define uv__req_unregister(loop, req)                                         \
  do {                                                                        \
    assert(uv__has_active_reqs(loop));                                        \
    QUEUE_REMOVE(&(req)->active_queue);                                       \
  }                                                                           \
  while (0)

#define uv__has_active_reqs(loop)                                             \
  (QUEUE_EMPTY(&(loop)->active_reqs) == 0)

#define QUEUE_EMPTY(q)                                                        \
  ((const QUEUE *) (q) == (const QUEUE *) QUEUE_NEXT(q))
```

To check the source code, it means the `active_reqs` is empty. 
What operation can cause this happen?

Thank you!

**Comment by bnoordhuis** [comment]
Can you report the exact libuv release?  "1.x" covers all releases from the last three years.

**Comment by saghul** [comment]
Are you calling any libuv functions from multiple threads?

**Comment by cjihrig** [comment]
No follow up. Closing.

**Comment by vertextao** [comment]
Sorry about forgotten this issue!
@saghul finally, I've figured out this issue is caused by call uv api from multiple threads.
Thanks!
