### ISSUE TITLE
uv_write causes coredump if the peer closed the tcp connection

### ISSUE THREAD

**Issue by CookieDSEU** [libuv/libuv#3044]
* **Version**: 1.x
* **Platform**: Linux *********** 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Hi all, I'm writing a high-performance rtsp server that needs to continue to send data to clients.
I used `uv_queue_work` to calculate frames data (Because it's heavy so I put it in the uv worker threads) and used `uv_after_work_cb` to write frames (so as to write data in the event loop).
I had some code like this:
```
if(uv_is_writable(stream))
{
    uv_write_t* writeRequest = new uv_write_t;
    uv_buf_t* buf = new uv_buf_t;
    buf->base = (char*)data;
    buf->len = dataLength;
    writeRequest->data = buf;
    uv_write(writeRequest, stream, buf, 1, tcp_write_cb);
}
```

However, it continued to coredump because of this:
```
#0  __libc_write (nbytes=1476, buf=0x7fffe4014f80, fd=52) at ../sysdeps/unix/sysv/linux/write.c:26
#1  __libc_write (fd=52, buf=0x7fffe4014f80, nbytes=1476) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x000000000044d876 in uv__writev (fd=52, vec=0x7ffff000ad10, n=1)
    at /home/peng.deng/CPPProjects/libuv/src/unix/stream.c:713
#3  0x000000000044de70 in uv__write (stream=0x7ffff0009110)
    at /home/peng.deng/CPPProjects/libuv/src/unix/stream.c:891
#4  0x000000000044f446 in uv_write2 (req=0x7ffff000ac90, stream=0x7ffff0009110, bufs=0x7ffff0008620,
    nbufs=1, send_handle=0x0, cb=0x4344b8 <tcp_write_cb(uv_write_s*, int)>)
    at /home/peng.deng/CPPProjects/libuv/src/unix/stream.c:1472
#5  0x000000000044f4e6 in uv_write (req=0x7ffff000ac90, handle=0x7ffff0009110, bufs=0x7ffff0008620,
    nbufs=1, cb=0x4344b8 <tcp_write_cb(uv_write_s*, int)>)
    at /home/peng.deng/CPPProjects/libuv/src/unix/stream.c:1497
#6  0x00000000004348e2 in TcpServer::writeData (this=0x7ffff7a1f9e0, stream=0x7ffff0009110,
    data=0x7fffe4014f80 "$", dataLength=1476)
    at /home/peng.deng/CPPProjects/vps-ai/src/transport/tcp_server.cpp:83
#7  0x0000000000435bf8 in sendFrame (req=0x7ffff0009580, status=0)
    at /home/peng.deng/CPPProjects/vps-ai/src/transport/rtsp_server.cpp:195
#8  0x000000000043efa3 in uv__queue_done (w=0x7ffff00095d8, err=0)
    at /home/peng.deng/CPPProjects/libuv/src/threadpool.c:334
#9  0x000000000043eed5 in uv__work_done (handle=0x7ffff7a1fb90)
    at /home/peng.deng/CPPProjects/libuv/src/threadpool.c:313
#10 0x0000000000443a05 in uv__async_io (loop=0x7ffff7a1fae0, w=0x7ffff7a1fca8, events=1)
    at /home/peng.deng/CPPProjects/libuv/src/unix/async.c:163
#11 0x000000000045578f in uv__io_poll (loop=0x7ffff7a1fae0, timeout=-1)
    at /home/peng.deng/CPPProjects/libuv/src/unix/linux-core.c:462
#12 0x00000000004443d4 in uv_run (loop=0x7ffff7a1fae0, mode=UV_RUN_DEFAULT)
---Type <return> to continue, or q <return> to quit---
   cts/libuv/src/unix/core.c:385
#13 0x000000000042b127 in <lambda()>::operator()(void) const (__closure=0x4d1978) at /home/peng.deng/CPPProjects/vps-ai/src/main.cpp:33
#14 0x000000000042d35e in std::_Bind_simple<main(int, char**)::<lambda()>()>::_M_invoke<>(std::_Index_tuple<>) (this=0x4d1978) at /usr/include/c++/4.9/functional:1700
#15 0x000000000042d1e6 in std::_Bind_simple<main(int, char**)::<lambda()>()>::operator()(void) (this=0x4d1978) at /usr/include/c++/4.9/functional:1688
#16 0x000000000042d0aa in std::thread::_Impl<std::_Bind_simple<main(int, char**)::<lambda()>()> >::_M_run(void) (this=0x4d1960) at /usr/include/c++/4.9/thread:115
#17 0x00007ffff7e59042 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007ffff7f72609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#19 0x00007ffff7c97103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I knew it's because the peer closed the connection so I failed to write to the `fd`.  Although I used `uv_is_writable` to check if the stream is writable, it doesn't seem to work. I also closed the stream when I read `EOF` from the tcp connection or write fail in the `tcp_write_cb`. It seems all of them were too late to mark the `uv_stream_t` is closed.
I have 2 questions:
1. Shouldn't `uv_write` return an error code rather than just coredump the program?
2. If I did something wrong, how can I immediately know that the tcp connection is closed by the client and cancel the pending writing requests that have been queued by `uv_write`?

**Comment by vtjnash** [comment]
That's not descriptive of the error. What coredump? Are you aware you need to block SIGPIPE (http://docs.libuv.org/en/v1.x/guide/filesystem.html)?

**Comment by CookieDSEU** [comment]
OK, that's exactly what I want. Thanks a lot.
