### ISSUE TITLE
uv-1.4.2 tcpclient crash

### ISSUE THREAD

**Issue by qq805005062** [libuv/libuv#3337]
Whether it is windows or Linux, as a TCP client, when the server fails to connect, the connection is requested every few seconds, and there is a certain probability of crash,

#0  0x0000000000592310 in ?? ()
#1  0x00000000004f52dc in uv__io_poll (loop=0x578c60 <default_loop_struct>, timeout=161) at /mnt/hgfs/workspace/metel_sdp/client/third_party/libuv-1.42.0/src/unix/epoll.c:374
#2  0x00000000004e1a28 in uv_run (loop=0x578c60 <default_loop_struct>, mode=UV_RUN_DEFAULT) at /mnt/hgfs/workspace/metel_sdp/client/third_party/libuv-1.42.0/src/unix/core.c:389
#3  0x00000000004d5b80 in uv::EventLoop::run (this=0x578a20 <uv::EventLoop::DefaultLoop()::defaultLoop>) at /mnt/hgfs/workspace/metel_sdp/client/third_party/uv-cpp1.5.4/uv/EventLoop.cpp:67
#4  0x00000000004153c6 in main () at /mnt/hgfs/workspace/metel_sdp/client/sdp/app/main.cpp:99
#5  0x00007ffff6be7555 in __libc_start_main (main=0x414f30 <main>, argc=1, argv=0x7fffffffe628, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe618) at ../csu/libc-start.c:266
#6  0x000000000041788f in _start () at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/basic_string.h:3901

**Comment by qq805005062** [comment]
Windows crash 
![1634700080(1)](https://user-images.githubusercontent.com/22863573/138023586-58bc2702-4df0-49f2-8de5-16795837110d.png)
